import { Inter} from "next/font/google";
import "./globals.css";
import Navbar from "../Components/navbar/Navbar";
import Contactfooter from "../Components/Footer/Contactfooter";
import Footer from "../Components/Footer/Footer";
import { ToastContainer } from "react-toastify";
import Tabbar from "@/Components/Tabbar/Tabbar";

const inter= Inter({ subsets: ['latin'] })
export const metadata = {
  title: "rentupbuild",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}   >
        <ToastContainer/>
        <Navbar/>
        {children}
         <Contactfooter/>
        <Footer />
        <Tabbar/>
      </body>
    </html>
  );
}
