// Importing the Inter font using Next.js font optimization
import { Inter } from "next/font/google";

// Importing global styles for the app
import "./globals.css";

// Importing layout components
import Navbar from "../Components/navbar/Navbar";
import Contactfooter from "../Components/Footer/Contactfooter";
import Footer from "../Components/Footer/Footer";
import Tabbar from "@/Components/Tabbar/Tabbar";

// Importing toast notification system
import { ToastContainer } from "react-toastify";

// Importing context provider for tab bar state management
import { MyProvider } from "@/contextApi/Tabcontext";

// Initialize Inter font with Latin subset
const inter = Inter({ subsets: ['latin'] });

// Metadata for the app, used by Next.js for SEO and document head
export const metadata = {
  title: "rentup", // Title shown in browser tab and search engines
  description: "Generated by create next app", // Basic description for SEO
};

// Root layout for the application
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}> {/* Applies the Inter font to the whole app */}
        <MyProvider> {/* Provides tab-related state to all child components */}
          <ToastContainer /> {/* Enables toast notifications across the app */}
          <Navbar /> {/* Top navigation bar */}

          {children} {/* Main page content injected here */}

          <Contactfooter /> {/* Optional contact-related footer section */}
          <Footer /> {/* Main footer */}
          <Tabbar /> {/* Bottom tab bar for navigation, mobile-focused */}
        </MyProvider>
      </body>
    </html>
  );
}
