import { Inter} from "next/font/google";
import "./globals.css";
import Navbar from "./Components/navbar/Navbar";
import Contactfooter from "./Contactfooter";
import Footer from "./Footer";
import { ToastContainer } from "react-toastify";

const inter= Inter({ subsets: ['latin'] })
export const metadata = {
  title: "rentupbuild",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}   >
        <ToastContainer/>
        <Navbar/>
        {children}
         <Contactfooter/>
        <Footer/>
      </body>
    </html>
  );
}
